<html>
    <body>
        <?php
        $i=100;
        printf("%d",$i);
        printf("<br>");
        printf("%f",$i);
        printf("<br>");
        printf("%s",$i);
        printf("<br>");
        $s="james";
        printf("%s",$s);
        printf("<br>");
        printf($s);printf("<br>");printf("%d",$s);
        ?>
    </body>
</html>